import type { Site, DomAudit, CredentialStatus, Project } from './tauri'

interface McpMetrics {
  gsc?: { clicks: number; impressions: number; ctr: number; position: number }
  cwv?: { lcp: number; cls: number; inp: number; ttfb: number }
}

function _siteOverviewLines(site: Site, project: Project | undefined, audit: DomAudit | null): string[] {
  const lines = ['## Site', `URL: ${site.url}`]
  if (project) lines.push(`Project: ${project.name}`)
  if (audit) {
    lines.push(`DOM Score: ${audit.score ?? 'n/a'}/100`)
    lines.push(`Last audited: ${new Date(audit.crawled_at).toLocaleDateString('es-ES')}`)
  } else {
    lines.push('DOM Score: not audited yet')
  }
  lines.push('')
  return lines
}

function _domIssuesLines(audit: DomAudit): string[] {
  const lines: string[] = ['## DOM Issues']
  if (!audit.issues.length) {
    lines.push('✓ No issues found')
  } else {
    const critical = audit.issues.filter(i => i.severity === 'critical')
    const warnings = audit.issues.filter(i => i.severity === 'warning')
    const info     = audit.issues.filter(i => i.severity === 'info')
    critical.forEach(i => lines.push(`🔴 [${i.category}] ${i.message}\n   Fix: ${i.fix}`))
    warnings.forEach(i => lines.push(`🟡 [${i.category}] ${i.message}\n   Fix: ${i.fix}`))
    info.forEach(i     => lines.push(`🔵 [${i.category}] ${i.message}\n   Fix: ${i.fix}`))
  }
  lines.push('', '## Technical SEO',
    `Title: "${audit.title ?? 'MISSING'}" (${audit.title_length ?? 0} chars)`,
    `Meta desc: ${audit.meta_description ? `${audit.meta_desc_length} chars` : 'MISSING'}`,
    `Canonical: ${audit.canonical ?? 'MISSING'} ${audit.canonical_match ? '✓' : '⚠ mismatch'}`,
    `H1: ${audit.h1_count ?? 0} found — "${audit.h1_text ?? ''}"`,
    `Meta robots: ${audit.meta_robots ?? 'not set'}`,
    `Schema types: ${audit.schema_types?.join(', ') || 'none'}`,
    `Hreflang: ${audit.hreflang_tags?.length ?? 0} tags`,
    `llms.txt: ${audit.llms_txt ? 'present ✓' : 'missing'}`,
    `Invalid head: ${audit.has_invalid_head ? 'YES ⚠' : 'no'}`,
    '')
  return lines
}

function _cwvLines(cwv: { lcp: number; cls: number; inp: number; ttfb: number }): string[] {
  const { lcp, cls, inp, ttfb } = cwv
  return [
    '## Core Web Vitals',
    `LCP:  ${lcp}s  ${lcp <= 2.5 ? '✓ GOOD' : lcp <= 4 ? '⚠ NEEDS WORK' : '🔴 POOR'}`,
    `CLS:  ${cls}   ${cls <= 0.1 ? '✓ GOOD' : cls <= 0.25 ? '⚠ NEEDS WORK' : '🔴 POOR'}`,
    `INP:  ${inp}ms ${inp <= 200 ? '✓ GOOD' : inp <= 500 ? '⚠ NEEDS WORK' : '🔴 POOR'}`,
    `TTFB: ${ttfb}ms ${ttfb <= 800 ? '✓ GOOD' : '⚠ NEEDS WORK'}`,
    '',
  ]
}

function _gscLines(gsc: { clicks: number; impressions: number; ctr: number; position: number }): string[] {
  const { clicks, impressions, ctr, position } = gsc
  return [
    '## Search Performance (GSC · last 28 days)',
    `Clicks: ${clicks.toLocaleString()} | Impressions: ${impressions.toLocaleString()} | CTR: ${ctr}% | Avg Position: ${position}`,
    '',
  ]
}

function _sourcesLines(credentials: CredentialStatus[], site: Site): string[] {
  const connected = credentials.filter(c => c.is_configured).map(c => c.service.toUpperCase())
  const missing   = credentials.filter(c => !c.is_configured).map(c => c.service.toUpperCase())
  const lines = ['## Data Sources']
  if (connected.length) lines.push(`✓ Connected: ${connected.join(', ')}`)
  if (missing.length)   lines.push(`✗ Not configured: ${missing.join(', ')}`)
  lines.push('', '## MCP Properties',
    `GSC: ${site.gsc_property ?? 'not set'}`,
    `GA4: ${site.ga4_property ?? 'not set'}`,
    `BWT: ${site.bwt_property ?? 'not set'}`,
    `Clarity: ${site.clarity_project ?? 'not set'}`)
  return lines
}

export function buildSiteContext(
  site: Site,
  project: Project | undefined,
  audit: DomAudit | null,
  credentials: CredentialStatus[],
  mcp: McpMetrics = {}
): string {
  const now = new Date().toLocaleString('es-ES')
  const lines: string[] = [
    `# SEO Analysis — ${site.domain}`,
    `Generated by SYNIO SEO Hub · ${now}`,
    '',
  ]
  lines.push(..._siteOverviewLines(site, project, audit))
  if (audit)   lines.push(..._domIssuesLines(audit))
  if (mcp.cwv) lines.push(..._cwvLines(mcp.cwv))
  if (mcp.gsc) lines.push(..._gscLines(mcp.gsc))
  lines.push(..._sourcesLines(credentials, site))
  return lines.join('\n')
}

export async function openInClaude(contextText: string): Promise<'opened' | 'copied'> {
  // Copy to clipboard
  await navigator.clipboard.writeText(contextText)

  // Try to open Claude Desktop via its URL scheme
  const IS_TAURI = Boolean((window as any).__TAURI_INTERNALS__)
  if (IS_TAURI) {
    try {
      const { open } = await import('@tauri-apps/plugin-shell')
      await open('claude://')
      return 'opened'
    } catch {
      // Claude Desktop not installed or no URL scheme — clipboard is enough
    }
  }

  return 'copied'
}
